networks:
  workshop:
services:
  servicems:
    image: juansehgu/services_ms
    container_name: serviceMS
    env_file:
        - ./.env
    environment:
      - SERVER_PORT=9000
    networks:
      - workshop
  contentsms:
    container_name: contentsMS
    env_file:
        - ./.env
    environment:
      - SERVER_PORT=9001
    build: ./contentsMS/
    networks:
      - workshop
  usersms:
    image: juansehgu/user_ms
    container_name: usersMS
    env_file:
      - ./.env
    environment:
      - SERVER_PORT=9002
      - DATA_SOURCE_URL=jdbc:mariadb://servicesms.cyon8lm0af1n.us-east-1.rds.amazonaws.com:3306/auth
    networks:
      - workshop
  reservems:
    image: juansehgu/reserve_ms
    container_name: reserveMS
    env_file:
      - ./.env
    environment:
      - SERVER_PORT=9003
      - URL_SERVICE=http://servicems:9000/services/
      - URL_CLIENT=http://usersms:9002/user/client/
    networks:
      - workshop
  gateway:
    image: juansehgu/gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SERVICES_URL=http://servicems:9000
      - CONTENTS_URL=http://contentsms:9001
      - USERS_URL=http://usersms:9002
      - RESERVES_URL=http://reservems:9003
    networks:
      - workshop
