version: "3.6"
networks:
  workshop:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
services:
  # --------EUREKAAAAAAAA_---------------
  eureka:
    container_name: eureka
    image: eclipse-temurin:17-jdk-alpine
    volumes:
      - ./eurekaserver/target/eurekaserver-0.0.1-SNAPSHOT.jar:/app/eureka.jar
    working_dir: /app/
    ports:
      - "8761:8761"
    command: java -jar eureka.jar --server.port=8761
    healthcheck:
      test: wget -qO- http://localhost:8761/eureka/apps || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      workshop:
        ipv4_address: 172.30.0.10

  # BASES DE DATOS
  dbServices:
    container_name: dbServices
    image: mariadb:latest
    ports:
      - "3306:3306"
    networks:
      workshop:
        ipv4_address: 172.30.0.2
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: services
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
  dbAuth:
    container_name: dbAuth
    image: mariadb:latest
    ports:
      - "3307:3306"
    networks:
      workshop:
        ipv4_address: 172.30.0.3
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: auth

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # ------------------------------------
  serviceMS:
    container_name: serviceMS
    image: eclipse-temurin:17-jdk-alpine
    working_dir: /app/
    restart: always
    volumes:
      - ./services/target/services-0.0.1-SNAPSHOT.jar:/app/services.jar
    depends_on:
      dbServices:
        condition: service_healthy
      eureka:
        condition: service_healthy
    ports:
      - "9000:9000"
    command: java -jar services.jar --registry.host=172.30.0.10 --server.port=9000 --registry.port=8761 --spring.datasource.password=root  --spring.datasource.username=root  --spring.datasource.url=jdbc:mariadb://172.30.0.2:3306/services
    networks:
      workshop:
        ipv4_address: 172.30.0.4

  contentsMS:
    container_name: contentsMS
    image: eclipse-temurin:17-jdk-alpine
    working_dir: /app/
    restart: always
    volumes:
      - ./contentsMS/target/contenidos-0.0.1-SNAPSHOT.jar:/app/contentsMS.jar
    depends_on:
      dbServices:
        condition: service_healthy
      eureka:
        condition: service_healthy
    ports:
      - "9001:9001"
    command: java -jar contentsMS.jar --registry.host=172.30.0.10 --registry.port=8761 --server.port=9001 --spring.datasource.password=root  --spring.datasource.username=root  --spring.datasource.url=jdbc:mariadb://172.30.0.2:3306/services
    networks:
      workshop:
        ipv4_address: 172.30.0.5
    # ------------------------------------
  usersMS:
    container_name: usersMS
    image: eclipse-temurin:17-jdk-alpine
    working_dir: /app/
    restart: always
    volumes:
      - ./userManagment/target/userManagment-0.0.1-SNAPSHOT.jar:/app/usersMS.jar
    depends_on:
      dbAuth:
        condition: service_healthy
      eureka:
        condition: service_healthy
    ports:
      - "9002:9002"
    command: java -jar usersMS.jar --server.port=9002  --registry.host=172.30.0.10 --registry.port=8761 --spring.datasource.password=root  --spring.datasource.username=root  --spring.datasource.url=jdbc:mariadb://172.30.0.3:3306/auth
    networks:
      workshop:
        ipv4_address: 172.30.0.6

  reserveMS:
    container_name: reserveMS
    image: eclipse-temurin:17-jdk-alpine
    working_dir: /app/
    restart: always
    volumes:
      - ./reserve/target/reserve-0.0.1-SNAPSHOT.jar:/app/reserve.jar
    depends_on:
      dbServices:
        condition: service_healthy
      eureka:
        condition: service_healthy
    ports:
      - "9003:9003"
    command: java -jar reserve.jar --registry.host=172.30.0.10 --registry.port=8761 --server.port=9003 --spring.datasource.password=root  --spring.datasource.username=root  --spring.datasource.url=jdbc:mariadb://172.30.0.3:3306/auth --urlService=http://172.30.0.4:9000/services/  --urlClient=http://172.30.0.6:9002/user/client/
    networks:
      workshop:
        ipv4_address: 172.30.0.7
  # ---------------------------------------------

