networks:
  workshop:
services:
  dbservices:
    container_name: dbServices
    build: ./db/
    networks:
      - workshop
    environment:
      MYSQL_DATABASE: services
  dbauth:
    container_name: dbAuth
    build: ./db/
    image: mariadb:latest
    networks:
      - workshop
    environment:
      MYSQL_DATABASE: auth
  servicems:
    container_name: serviceMS
    restart: always
    environment:
      - DATA_SOURCE_URL=jdbc:mariadb://dbservices:3306/services
      - SERVER_PORT=9000
    build: ./services/
    depends_on:
      dbservices:
        condition: service_healthy
    networks:
      - workshop
  contentsms:
    container_name: contentsMS
    restart: always
    environment:
      - DATA_SOURCE_URL=jdbc:mariadb://dbservices:3306/services
      - SERVER_PORT=9001
    build: ./contentsMS/
    depends_on:
      dbservices:
        condition: service_healthy
    networks:
      - workshop
  usersms:
    container_name: usersMS
    restart: always
    environment:
      - DATA_SOURCE_URL=jdbc:mariadb://dbauth:3306/auth
      - SERVER_PORT=9002
    build: ./userManagment/
    depends_on:
      dbauth:
        condition: service_healthy
    networks:
      - workshop
  reservems:
    container_name: reserveMS
    restart: always
    environment:
      - DATA_SOURCE_URL=jdbc:mariadb://dbservices:3306/services
      - SERVER_PORT=9003
      - URL_SERVICE=http://servicems:9000/services/
      - URL_CLIENT=http://userms:9002/user/client/
    build: ./reserve/
    depends_on:
      dbservices:
        condition: service_healthy
    networks:
      - workshop
  gateway:
    container_name: gateway
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SERVICES_URL=http://servicems:9000
      - CONTENTS_URL=http://contentsms:9001
      - USERS_URL=http://usersms:9002
      - RESERVES_URL=http://reservems:9003
    build: ./gateway/
    networks:
      - workshop
