spring:
  cloud:
    gateway:
      routes:
        - id: services
          uri: ${SERVICES_URL}
          predicates:
            - Path=/services/**
        - id: contents
          uri: ${CONTENTS_URL}
          predicates:
            - Path=/contents/**
        - id: users
          uri: ${USERS_URL}
          predicates:
            - Path=/user/**
        - id: reserve
          uri: ${RESERVES_URL}
          predicates:
            - Path=/reserve/**

